DROP SEQUENCE SEQ_FACILITY_TYPE;
DROP SEQUENCE SEQ_FILE_INFO;
DROP SEQUENCE SEQ_MEET_FACILITY;
DROP SEQUENCE SEQ_MEETING_APPLY;
DROP SEQUENCE SEQ_MEETING_ROOM;
DROP SEQUENCE SEQ_MODULE_GROUP;
DROP SEQUENCE SEQ_MODULE_INFO;
DROP SEQUENCE SEQ_ROLE_INFO;
DROP SEQUENCE SEQ_USER_INFO;

CREATE SEQUENCE SEQ_FACILITY_TYPE	INCREMENT BY 1 START WITH 1 MAXVALUE 100000000 MINVALUE 1 NOCYCLE CACHE 20 ORDER;
CREATE SEQUENCE SEQ_FILE_INFO		INCREMENT BY 1 START WITH 1 MAXVALUE 100000000 MINVALUE 1 NOCYCLE CACHE 20 ORDER;
CREATE SEQUENCE SEQ_MEET_FACILITY	INCREMENT BY 1 START WITH 1 MAXVALUE 100000000 MINVALUE 1 NOCYCLE CACHE 20 ORDER;
CREATE SEQUENCE SEQ_MEETING_APPLY	INCREMENT BY 1 START WITH 1 MAXVALUE 100000000 MINVALUE 1 NOCYCLE CACHE 20 ORDER;
CREATE SEQUENCE SEQ_MEETING_ROOM	INCREMENT BY 1 START WITH 1 MAXVALUE 100000000 MINVALUE 1 NOCYCLE CACHE 20 ORDER;
CREATE SEQUENCE SEQ_MODULE_GROUP	INCREMENT BY 1 START WITH 1 MAXVALUE 100000000 MINVALUE 1 NOCYCLE CACHE 20 ORDER;
CREATE SEQUENCE SEQ_MODULE_INFO		INCREMENT BY 1 START WITH 1 MAXVALUE 100000000 MINVALUE 1 NOCYCLE CACHE 20 ORDER;
CREATE SEQUENCE SEQ_ROLE_INFO		INCREMENT BY 1 START WITH 1 MAXVALUE 100000000 MINVALUE 1 NOCYCLE CACHE 20 ORDER;
CREATE SEQUENCE SEQ_USER_INFO		INCREMENT BY 1 START WITH 1 MAXVALUE 100000000 MINVALUE 1 NOCYCLE CACHE 20 ORDER;
