client: 
	g++ -g -o WebTableWriter -I/usr/local/include/thrift/ -I./ -L/usr/local/lib/ -lthrift WebTableWriter.h WebTableWriter.cpp WebTableWriterTest.cpp Hbase.cpp Hbase_types.cpp Hbase_constants.cpp
