-- Drop table
drop table filedept;
drop table abcfolder;
drop table userdept;
drop table userpower;
drop table words;
drop table filefolder;
drop table logcontent;
drop table scan;
drop table abcfile;
drop table usertable;
drop table department;
drop table abclogs;
